import sqlite3
conn = sqlite3.connect('数据缓存/stock_cache.db')
cur = conn.cursor()
cur.execute('SELECT code, code_name, industry FROM stock_industry LIMIT 10')
for r in cur.fetchall(): print(r)
print('---')
cur.execute('SELECT count(*) FROM stock_industry')
print('Total records:', cur.fetchone())
cur.execute('SELECT code, code_name, industry FROM stock_industry WHERE code LIKE "%0006%"')
rows = cur.fetchall()
print('0006 matches:', rows[:5])
cur.execute('SELECT DISTINCT industry FROM stock_industry LIMIT 20')
industries = cur.fetchall()
print('Sample industries:', industries[:10])
conn.close()
